# jam/samples

CXXFLAGS = -g -O0 -Wall -Werror -W `urg_c-config --cflags`
LDFLAGS =
#LDLIBS = `urg_c-config --libs`
LDLIBS = -lurg_c

TARGET = get_multiecho

all : $(TARGET)

clean :
	$(RM) $(TARGET) *.o
